# How to import Data Outputs 

When working with the output CSV files, note that leading zeros in some columns (e.g., StateFIPS, LEADID, CensusTract, County) may be dropped when the data is re-imported due to how Pandas and CSV files handle numerical data. To ensure consistency and preserve leading zeros, you must use the pad_column_values function.

In [1]:
import os
import chardet
import pandas as pd

from my_functions import pad_column_values

In [2]:
current_directory = os.getcwd()
print(current_directory)

/Users/alejandrocontreras/Desktop/Realizing_Rights/FCC_by_school_district

### Non-Aggregated Data Outputs 
*Note, extremely large when a single file. Consequently, import using parts and using chunks*

In [3]:
# Directory containing the split files
input_dir = "data_outputs/internet_access_nonaggregated"

# List all CSV files in the directory
file_paths = [os.path.join(input_dir, file) for file in os.listdir(input_dir) if file.endswith('.csv')]

# Read and concatenate the files
chunks = []
try:
    for file_path in file_paths:
        for chunk in pd.read_csv(file_path, chunksize=100000, encoding='ISO-8859-1', on_bad_lines='skip'):
            chunks.append(chunk)

    # Combine all chunks into a single DataFrame
    data = pd.concat(chunks, ignore_index=True)
    print("Files combined and loaded successfully.")
except UnicodeDecodeError as e:
    print(f"UnicodeDecodeError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

# Pad columns
data = pad_column_values(data, "StateFIPS", 2)
data = pad_column_values(data, "County", 5)
data = pad_column_values(data, "CensusTract", 11)
data = pad_column_values(data, "CensusBlock", 4)
data = pad_column_values(data, "LEADID", 7)

# View data
print(data.head(5))

Files combined and loaded successfully.
Ensuring 'StateFIPS' values are treated as strings.
Character counts for 'StateFIPS' before padding:
StateFIPS
1     8293603
2    47715940
Name: count, dtype: int64
Applied padding to 'StateFIPS' using '0' to reach 2 characters.
All 'StateFIPS' values are now exactly 2 characters long.

Ensuring 'County' values are treated as strings.
Character counts for 'County' before padding:
County
4     8293603
5    47715940
Name: count, dtype: int64
Applied padding to 'County' using '0' to reach 5 characters.
All 'County' values are now exactly 5 characters long.

Ensuring 'CensusTract' values are treated as strings.
Character counts for 'CensusTract' before padding:
CensusTract
10     8293603
11    47715940
Name: count, dtype: int64
Applied padding to 'CensusTract' using '0' to reach 11 characters.
All 'CensusTract' values are now exactly 11 characters long.

Ensuring 'CensusBlock' values are treated as strings.
Character counts for 'CensusBlock' before padding:
CensusBlock
1        2170
2        1664
3         119
4    56005590
Name: count, dtype: int64
Applied padding to 'CensusBlock' using '0' to reach 4 characters.
All 'CensusBlock' values are now exactly 4 characters long.

Ensuring 'LEADID' values are treated as strings.
Character counts for 'LEADID' before padding:
LEADID
6     8293603
7    47715940
Name: count, dtype: int64
Applied padding to 'LEADID' using '0' to reach 7 characters.
All 'LEADID' values are now exactly 7 characters long.

                       NAME_LEA21  COUNT  LANDAREA  WATERAREA   LEADID  \
0  Autauga County School District     17  3.793571   0.010979  0100240
1  Autauga County School District     17  3.793571   0.010979  0100240
2  Autauga County School District     17  3.793571   0.010979  0100240
3  Autauga County School District     17  3.793571   0.010979  0100240
4  Autauga County School District     17  3.793571   0.010979  0100240

   CensusTract  LogRecNo  HocoNum       BlockCode  TechCode  Consumer  \
0  01001020100  25169438   130235  10010201002011        43         1
1  01001020100   4465048   130077  10010201001022        11         1
2  01001020100   7516096   420017  10010201001022        50         1
3  01001020100  29444936   130403  10010201001022        70         1
4  01001020100   8574333   131480  10010201001022        42         1

   MaxAdDown  MaxAdUp  Business  Zoom_Min_5_5_MBPS  \
0     1000.0     35.0         0                  1
1       12.0      1.5         0                  1
2     1000.0   1000.0         1                  1
3       25.0      3.0         1                  1
4     1000.0     50.0         0                  1

   FCC_Def_High_Speed_25_3_MBPS  Other_Def_High_Speed_100_20_MBPS StateFIPS  \
0                             1                                 1        01
1                             0                                 0        01
2                             1                                 1        01
3                             1                                 0        01
4                             1                                 1        01

  County CensusBlock
0  01001        2011
1  01001        1022
2  01001        1022
3  01001        1022
4  01001        1022

### Aggregated Data Outputs

In [4]:
# File 1: school_district_name.csv
file_path = "data_outputs/internet_access_aggregated/school_district_name.csv"
data = pd.read_csv(file_path)
data = pad_column_values(data, "StateFIPS", 2)
data.head(5)

Ensuring 'StateFIPS' values are treated as strings.
Character counts for 'StateFIPS' before padding:
StateFIPS
1     1952
2    11233
Name: count, dtype: int64
Applied padding to 'StateFIPS' using '0' to reach 2 characters.
All 'StateFIPS' values are now exactly 2 characters long.

,NAME_LEA21,StateFIPS,n_school_districts,n_counties,n_tracts,n_blocks,n_ISPs,zoom_5_5_coverage_pct,fcc_25_3_coverage_pct,other_100_20_coverage_pct,...,median_MaxAdDown,mean_MaxAdDown,min_MaxAdDown,std_MaxAdDown,max_MaxAdUp,median_MaxAdUp,mean_MaxAdUp,min_MaxAdUp,std_MaxAdUp,n_LEADIDs
0,A-C Central Community Unit School District 262,17,1,4,6,646,16,0.568012,0.426597,0.077827,...,10.0,58.527860,0.0,188.992376,1000.0,1.0,26.583331,0.0,147.145622,1
1,A.C.G.C. Public School District,27,1,2,5,545,20,0.963367,0.779149,0.312763,...,50.0,126.634257,0.0,232.631802,1000.0,10.0,63.091471,0.0,160.067268,1
2,ABC Unified School District,06,1,1,31,169,25,0.751899,0.481872,0.337880,...,18.0,377.096698,0.0,545.801691,2000.0,1.0,199.312841,0.0,471.525500,1
3,AGWSR Community School District,19,1,4,8,688,26,0.775376,0.701997,0.435049,...,50.0,149.141764,0.0,250.065814,1000.0,10.0,67.647188,0.0,132.490438,1
4,AHSTW Community School District,19,1,4,8,894,22,0.630569,0.562197,0.289259,...,25.0,165.052051,0.0,321.096459,1000.0,4.0,122.063855,0.0,309.719416,1

In [5]:
# File 2: school_district_LEADID.csv
file_path = "data_outputs/internet_access_aggregated/school_district_LEADID.csv"
data = pd.read_csv(file_path)
data = pad_column_values(data, "LEADID", 7)
data.head(5)

Ensuring 'LEADID' values are treated as strings.
Character counts for 'LEADID' before padding:
LEADID
6     1966
7    11294
Name: count, dtype: int64
Applied padding to 'LEADID' using '0' to reach 7 characters.
All 'LEADID' values are now exactly 7 characters long.

,LEADID,StateFIPS,n_school_districts,n_counties,n_tracts,n_blocks,n_ISPs,zoom_5_5_coverage_pct,fcc_25_3_coverage_pct,other_100_20_coverage_pct,...,median_MaxAdDown,mean_MaxAdDown,min_MaxAdDown,std_MaxAdDown,max_MaxAdUp,median_MaxAdUp,mean_MaxAdUp,min_MaxAdUp,std_MaxAdUp,n_LEADIDs
0,0100001,1,1,2,2,262,6,0.824204,0.663694,0.438217,...,25.0,444.501646,0.0,488.087805,1000.0,3.0,116.887977,0.0,301.476415,1
1,0100003,1,1,1,2,96,9,0.864865,0.835135,0.589189,...,1000.0,595.702703,0.0,484.893739,1000.0,35.0,40.386616,0.0,124.956767,1
2,0100005,1,1,1,9,341,13,0.929194,0.783330,0.486073,...,50.0,486.356287,0.0,488.574145,1000.0,15.0,198.544367,0.0,383.460483,1
3,0100006,1,1,1,26,406,16,0.948284,0.822993,0.458376,...,30.0,462.947366,0.0,485.953751,1000.0,15.0,182.454809,0.0,369.468085,1
4,0100007,1,1,2,39,324,19,0.882177,0.686460,0.396212,...,25.0,345.094862,0.0,454.082998,1000.0,4.0,88.454637,0.0,261.414861,1

In [6]:
# File 3: census_tract_level.csv
file_path = "data_outputs/internet_access_aggregated/census_tract_level.csv"
data = pd.read_csv(file_path)
data = pad_column_values(data, "CensusTract", 11)
data = pad_column_values(data, "StateFIPS", 2)
data.head(5)

Ensuring 'CensusTract' values are treated as strings.
Character counts for 'CensusTract' before padding:
CensusTract
10    15628
11    69640
Name: count, dtype: int64
Applied padding to 'CensusTract' using '0' to reach 11 characters.
All 'CensusTract' values are now exactly 11 characters long.

Ensuring 'StateFIPS' values are treated as strings.
Character counts for 'StateFIPS' before padding:
StateFIPS
1    15628
2    69640
Name: count, dtype: int64
Applied padding to 'StateFIPS' using '0' to reach 2 characters.
All 'StateFIPS' values are now exactly 2 characters long.

,CensusTract,StateFIPS,n_school_districts,n_counties,n_tracts,n_blocks,n_ISPs,zoom_5_5_coverage_pct,fcc_25_3_coverage_pct,other_100_20_coverage_pct,...,median_MaxAdDown,mean_MaxAdDown,min_MaxAdDown,std_MaxAdDown,max_MaxAdUp,median_MaxAdUp,mean_MaxAdUp,min_MaxAdUp,std_MaxAdUp,n_LEADIDs
0,01001020100,01,1,1,1,51,6,0.890805,0.741379,0.494253,...,50.0,487.546391,0.0,491.006521,1000.0,10.0,64.786230,0.0,206.773327,1
1,01001020200,01,1,1,1,41,8,0.867403,0.651934,0.453039,...,25.0,461.461326,0.0,491.536786,1000.0,3.0,41.246696,0.0,145.992239,1
2,01001020300,01,1,1,1,42,8,0.856164,0.746575,0.527397,...,1000.0,534.525808,0.0,493.465745,1000.0,35.0,48.927945,0.0,161.454164,1
3,01001020400,01,1,1,1,91,6,0.720690,0.672414,0.606897,...,1000.0,609.669655,0.0,485.881185,1000.0,35.0,39.460938,0.0,115.690142,1
4,01001020501,01,1,1,1,46,8,0.935345,0.758621,0.461207,...,50.0,419.814655,0.0,476.088439,1000.0,10.0,77.795121,0.0,234.921280,1

In [7]:
# File 4: county_level.csv
file_path = "data_outputs/internet_access_aggregated/county_level.csv"
data = pd.read_csv(file_path)
data = pad_column_values(data, "County", 5)
data = pad_column_values(data, "StateFIPS", 2)
data.head(5)

Ensuring 'County' values are treated as strings.
Character counts for 'County' before padding:
County
4     317
5    2914
Name: count, dtype: int64
Applied padding to 'County' using '0' to reach 5 characters.
All 'County' values are now exactly 5 characters long.

Ensuring 'StateFIPS' values are treated as strings.
Character counts for 'StateFIPS' before padding:
StateFIPS
1     317
2    2914
Name: count, dtype: int64
Applied padding to 'StateFIPS' using '0' to reach 2 characters.
All 'StateFIPS' values are now exactly 2 characters long.

,County,StateFIPS,n_school_districts,n_counties,n_tracts,n_blocks,n_ISPs,zoom_5_5_coverage_pct,fcc_25_3_coverage_pct,other_100_20_coverage_pct,...,median_MaxAdDown,mean_MaxAdDown,min_MaxAdDown,std_MaxAdDown,max_MaxAdUp,median_MaxAdUp,mean_MaxAdUp,min_MaxAdUp,std_MaxAdUp,n_LEADIDs
0,01001,01,1,1,17,245,13,0.889755,0.732756,0.474459,...,25.0,466.639576,0.0,488.029235,1000.0,5.0,141.180867,0.0,327.199673,1
1,01003,01,2,1,43,503,25,0.894018,0.737575,0.438227,...,40.0,287.892630,0.0,390.332115,2000.0,5.0,65.379975,0.0,208.309077,2
2,01005,01,2,1,9,238,12,0.899752,0.644631,0.329299,...,25.0,324.496217,0.0,453.797858,1000.0,3.0,29.043104,0.0,127.666541,2
3,01007,01,1,1,8,234,13,0.909035,0.570375,0.089121,...,25.0,82.492846,0.0,235.951591,1000.0,2.0,64.277260,0.0,237.626448,1
4,01009,01,2,1,16,379,11,0.966887,0.773888,0.298644,...,25.0,225.070888,0.0,365.597489,1000.0,5.0,95.286887,0.0,278.367964,2

In [8]:
# File 5: state_level.csv
file_path = "data_outputs/internet_access_aggregated/state_level.csv"
data = pd.read_csv(file_path)
data = pad_column_values(data, "StateFIPS", 2)
data.head(5)

Ensuring 'StateFIPS' values are treated as strings.
Character counts for 'StateFIPS' before padding:
StateFIPS
1     7
2    49
Name: count, dtype: int64
Applied padding to 'StateFIPS' using '0' to reach 2 characters.
All 'StateFIPS' values are now exactly 2 characters long.

,StateFIPS,n_school_districts,n_counties,n_tracts,n_blocks,n_ISPs,zoom_5_5_coverage_pct,fcc_25_3_coverage_pct,other_100_20_coverage_pct,max_MaxAdDown,median_MaxAdDown,mean_MaxAdDown,min_MaxAdDown,std_MaxAdDown,max_MaxAdUp,median_MaxAdUp,mean_MaxAdUp,min_MaxAdUp,std_MaxAdUp,n_LEADIDs
0,01,140,67,1434,975,84,0.904069,0.707782,0.406381,2000.0,25.0,387.348205,0.0,493.401404,2000.0,4.0,111.487430,0.0,295.005233,140
1,02,53,30,176,1343,31,0.769430,0.555066,0.333724,2000.0,25.0,417.763404,0.0,767.605791,1000.0,4.0,33.480798,0.0,106.514491,53
2,04,216,15,1754,2195,100,0.913858,0.635316,0.262539,5000.0,25.0,223.571473,0.0,387.787610,5000.0,5.0,39.024301,0.0,167.643484,216
3,05,233,75,823,1352,96,0.930102,0.710062,0.349911,10000.0,30.0,305.340875,0.0,538.758187,10000.0,5.0,148.934512,0.0,455.633456,235
4,06,966,58,9115,2913,212,0.856154,0.665164,0.379331,10000.0,25.0,243.892836,0.0,556.328491,10000.0,4.0,91.720212,0.0,444.719095,978